### ISSUE TITLE
[DI][Test] Write tests for compiler passes and extension

### ISSUE THREAD

**Issue by cleentfaar** [treehouselabs/queue-bundle#23]
We should write some tests for the extension and compiler passes: https://github.com/matthiasnoback/SymfonyDependencyInjectionTest

**Comment by pkruithof** [comment]
The extension is fully tested already. But the compiler passes need tests, agreed.

**Comment by cleentfaar** [comment]
To clarify; I mean unit-tested.

**Comment by pkruithof** [comment]
https://github.com/treehouselabs/queue-bundle/blob/master/src/TreeHouse/QueueBundle/Tests/DependencyInjection/TreeHouseQueueExtensionTest.php

**Comment by cleentfaar** [comment]
My bad, was looking at the `tests` dir, strange that there are 2 directories for this...

Maybe we should fix that too then?

**Comment by pkruithof** [comment]
https://github.com/treehouselabs/queue-bundle/pull/22/files#diff-2056f0e0c69b177eb9cb40ddfb78e8ea

**Comment by cleentfaar** [comment]
<img src="http://nation.foxnews.com/sites/nation.foxnews.com/files/styles/story_624_300/public/homer_doh_fox_1.jpg"/>

**Comment by pkruithof** [comment]
Done.
